"""Add pricing_strategy

Revision ID: 877fb41b68a1
Revises: ddfd44a3a37e
Create Date: 2026-01-08 22:51:54.723957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877fb41b68a1'
down_revision = 'ddfd44a3a37e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pricing_strategy', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.drop_column('pricing_strategy')

    # ### end Alembic commands ###
