"""add subscription fields to restaurante

Revision ID: 9075edfa6a5b
Revises: b17a080954d4
Create Date: 2026-01-08 21:53:44.784684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9075edfa6a5b'
down_revision = 'b17a080954d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('subscription_tier', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurante', schema=None) as batch_op:
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('subscription_tier')
        batch_op.drop_column('subscription_status')

    # ### end Alembic commands ###
