"""fix fornecedor unique constraint

Revision ID: b17a080954d4
Revises: 7fc1334eef20
Create Date: 2026-01-08 21:37:07.389871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17a080954d4'
down_revision = '7fc1334eef20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedor', schema=None) as batch_op:
        batch_op.drop_index('ix_fornecedor_cnpj')
        batch_op.create_index(batch_op.f('ix_fornecedor_cnpj'), ['cnpj'], unique=False)
        batch_op.create_unique_constraint('uq_fornecedor_cnpj_restaurant', ['cnpj', 'restaurant_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedor', schema=None) as batch_op:
        batch_op.drop_constraint('uq_fornecedor_cnpj_restaurant', type_='unique')
        batch_op.drop_index(batch_op.f('ix_fornecedor_cnpj'))
        batch_op.create_index('ix_fornecedor_cnpj', ['cnpj'], unique=False)

    # ### end Alembic commands ###
