"""add inflation fields to produto

Revision ID: ddfd44a3a37e
Revises: 9075edfa6a5b
Create Date: 2026-01-08 22:01:46.578839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddfd44a3a37e'
down_revision = '9075edfa6a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_custo_anterior', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('variacao_preco_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('data_alerta_inflacao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('data_alerta_inflacao')
        batch_op.drop_column('variacao_preco_pct')
        batch_op.drop_column('ultimo_custo_anterior')

    # ### end Alembic commands ###
